Repository GNU-CapstoneDesign-II/G-Learn-E-BE, pull requests merged in 2025-04, with the labels that each got.

#24 Feat/public workbook imp #18
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/controller/PublicFolderController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/dto/response/CollegeResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/dto/response/DepartmentResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/dto/response/SubjectResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/dto/response/SubjectWorkbookResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/dto/response/WorkbookResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/DepartmentRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/SubjectRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/SubjectWorkbookMapRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/service/PublicFolderService.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/repository/WorkbookRepository.java
Labels: :sparkles: Feat

#27 [FEAT #25] 경상대 시간표 Json 업로드
  src/main/java/gnu/capstone/G_Learn_E/GLearnEApplication.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/entity/College.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/entity/Department.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/entity/Subject.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/CollegeRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/DepartmentRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/SubjectRepository.java
  src/main/java/gnu/capstone/G_Learn_E/global/file_upload/controller/FileUploadController.java
  src/main/java/gnu/capstone/G_Learn_E/global/file_upload/service/FileUploadService.java
Labels: :sparkles: Feat

#29 [Feat #28] FastAPI 연동 및 ApiResponse 적용 리팩토링
  src/main/java/gnu/capstone/G_Learn_E/GLearnEApplication.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/controller/PublicFolderController.java
  src/main/java/gnu/capstone/G_Learn_E/global/auth/controller/AuthController.java
  src/main/java/gnu/capstone/G_Learn_E/global/config/RestTemplateConfig.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/controller/FastApiController.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/request/GradeBlankRequest.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/request/GradeDescriptiveRequest.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/request/ProblemGenerateRequest.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/response/ApiLogResponse.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/response/GradeBlankResponse.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/response/GradeDescriptiveResponse.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/response/ProblemGenerateResponse.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/response/TokenUsageResponse.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/entity/FastApiProperties.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/enums/PeriodType.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/service/FastApiService.java
  src/main/java/gnu/capstone/G_Learn_E/global/jwt/JwtAuthenticationFilter.java
  src/main/java/gnu/capstone/G_Learn_E/global/security/SecurityConfig.java
  src/main/java/gnu/capstone/G_Learn_E/global/security/SecurityPathProperties.java
  src/main/java/gnu/capstone/G_Learn_E/global/security/exception/handler/CustomAccessDeniedHandler.java
  src/main/java/gnu/capstone/G_Learn_E/global/template/ApiResponse.java
  src/main/resources/application.yml
Labels: :sparkles: Feat

#32 [Refactor #31] 교과목 엔티티에 학년 필드 추가
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/dto/response/SubjectResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/entity/Subject.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/enums/SubjectGrade.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/SubjectRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/service/PublicFolderService.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/exception/.gitkeep
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/repository/.gitkeep
  src/main/java/gnu/capstone/G_Learn_E/global/file_upload/service/FileUploadService.java
Labels: :sparkles: Feat, 🔨 Refactor

#34 [Fix #33] 단과대 조회 값 변경
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/dto/response/CollegeResponse.java
Labels: :hammer_and_wrench: Fix

#36 [Feat #35] 도커 세팅
  .gitattributes
  DockerFile
  build.gradle
  wait-for-it.sh
Labels: :sparkles: Feat, :hammer_and_wrench: Fix

#37 [Feat #30] 문제집 생성 API 개발
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/entity/Folder.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/entity/FolderWorkbookId.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/entity/FolderWorkbookMap.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/repository/FolderRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/dto/response/ProblemResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/entity/Problem.java
  src/main/java/gnu/capstone/G_Learn_E/domain/user/entity/User.java
  src/main/java/gnu/capstone/G_Learn_E/domain/user/service/UserService.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/converter/WorkbookConverter.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/Content.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/ProblemGenerateRequest.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/QuestionTypes.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/ProblemGenerateResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/entity/Workbook.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/enums/ExamType.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/enums/Semester.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/controller/FastApiController.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/request/AudioToStringRequest.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/request/FastApiProblemGenerateRequest.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/request/PdfToStringRequest.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/dto/response/PdfToStringResponse.java
  src/main/java/gnu/capstone/G_Learn_E/global/fastapi/service/FastApiService.java
  src/main/resources/application.yml
Labels: :sparkles: Feat

#39 Feat/user service #26
  src/main/java/gnu/capstone/G_Learn_E/domain/notification/controller/NotificationController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/notification/dto/.gitkeep
  src/main/java/gnu/capstone/G_Learn_E/domain/notification/dto/response/NotificationResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/notification/repository/NotificationRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/notification/service/NotificationService.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
  src/main/java/gnu/capstone/G_Learn_E/domain/user/controller/UserController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/user/dto/.gitkeep
  src/main/java/gnu/capstone/G_Learn_E/domain/user/dto/request/GainExpRequest.java
  src/main/java/gnu/capstone/G_Learn_E/domain/user/dto/request/NicknameUpdateRequest.java
  src/main/java/gnu/capstone/G_Learn_E/domain/user/dto/response/UserInfoResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/user/entity/User.java
  src/main/java/gnu/capstone/G_Learn_E/domain/user/repository/UserRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/user/service/UserService.java
  src/main/java/gnu/capstone/G_Learn_E/global/auth/controller/AuthController.java
  src/main/resources/application.yml
Labels: :sparkles: Feat

#40 [Feat #38] 유저 폴더링 시스템
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/controller/FolderController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/.gitkeep
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/request/CreateFolderRequest.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/request/MoveFolderRequest.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/request/RenameFolderRequest.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/response/FolderResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/response/FolderTreeResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/response/FolderWorkbookRemoveResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/dto/response/SimpleFolderResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/entity/Folder.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/repository/FolderRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/repository/FolderWorkbookMapRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/service/FolderService.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/entity/Workbook.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
Labels: :sparkles: Feat

#42 [Feat #41] 생성된 문제집 문제 조회 API
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/controller/ProblemController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/dto/response/ProblemResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/dto/response/ProblemSolvePageResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/entity/Problem.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/repository/ProblemRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/service/ProblemService.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/dto/response/SolveLogResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/entity/SolveLog.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/entity/SolvedWorkbook.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/entity/SolvedWorkbookId.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/enums/SolvingStatus.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/repository/SolveLogRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/repository/SolvedWorkbookRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/converter/WorkbookConverter.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
Labels: :sparkles: Feat, 🔨 Refactor

#43 [Feat #41] 문제 풀이 임시 저장 및 정답 제출 여부 response 개선
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/controller/ProblemController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/controller/SolveLogController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/dto/request/SaveSolveLogRequest.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/dto/request/SolveLogRequest.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/entity/SolveLog.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
Labels: :sparkles: Feat, 🔨 Refactor

#44 [Refactor #41] 문제 풀이 페이지 API 도메인 변경
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/controller/ProblemController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/converter/WorkbookConverter.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookSolveResponse.java
Labels: 🔨 Refactor

#45 [Feat #41] 문제 풀이 기록 초기화 API 추가
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/controller/SolveLogController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
Labels: :sparkles: Feat

#46 [Feat #41] 문제 풀이 채점 API 추가
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/entity/SolveLog.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/entity/SolvedWorkbook.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/GradeWorkbookResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/repository/WorkbookRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
Labels: :sparkles: Feat

#53 [Refactor #52] 문제, 문제집 N:M 매핑 리팩토링 및 고아 엔티티 정리 기능 추가
  src/main/java/gnu/capstone/G_Learn_E/GLearnEApplication.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/dto/response/ProblemResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/entity/Problem.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/entity/ProblemWorkbookMap.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/repository/ProblemRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/repository/ProblemWorkbookMapRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/service/ProblemService.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/converter/WorkbookConverter.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/entity/Workbook.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/repository/WorkbookRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
  src/main/java/gnu/capstone/G_Learn_E/global/admin/AdminController.java
  src/main/java/gnu/capstone/G_Learn_E/global/admin/dto/CleanupResult.java
  src/main/java/gnu/capstone/G_Learn_E/global/scheduler/OrphanCleanupScheduler.java
Labels: :sparkles: Feat, 🔨 Refactor

#54 [Feat #51] 공개 문제집 업로드/다운로드 및 병합 기능 구현
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/repository/FolderRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/service/FolderService.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/converter/ProblemConverter.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/dto/request/ProblemRequest.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/enums/ProblemType.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/repository/ProblemRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/problem/service/ProblemService.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/controller/PublicFolderController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/dto/response/WorkbookResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/entity/SubjectWorkbookId.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/entity/SubjectWorkbookMap.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/DepartmentRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/SubjectRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/repository/SubjectWorkbookMapRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/service/PublicFolderService.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/controller/SolveLogController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/service/SolveLogService.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/.gitkeep
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/WorkbookMergeRequest.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/WorkbookUpload.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/request/WorkbookUploadList.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookDownloadResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookMergePageResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/dto/response/WorkbookUploadResponse.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/entity/Workbook.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/repository/WorkbookRepository.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/service/WorkbookService.java
Labels: :sparkles: Feat, 🔨 Refactor

#56 [Feat #55] Swagger 세팅
  build.gradle
  src/main/java/gnu/capstone/G_Learn_E/domain/folder/controller/FolderController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/notification/controller/NotificationController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/public_folder/controller/PublicFolderController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/solve_log/controller/SolveLogController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/user/controller/UserController.java
  src/main/java/gnu/capstone/G_Learn_E/domain/workbook/controller/WorkbookController.java
  src/main/java/gnu/capstone/G_Learn_E/global/admin/AdminController.java
  src/main/java/gnu/capstone/G_Learn_E/global/auth/controller/AuthController.java
  src/main/java/gnu/capstone/G_Learn_E/global/config/SwaggerConfig.java
  src/main/java/gnu/capstone/G_Learn_E/global/file_upload/controller/FileUploadController.java
Labels: :sparkles: Feat
